#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages, lets
# install one!

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
service nginx start
