#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
echo "frontend miguelcipamocha.tech
    bind *:80
    default_backend web_servers
backend web_servers
    balance roundrobin
    server 1565-web-02 35.237.227.219:80 check
    server 1565-web-01 35.231.180.109:80 check" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null 2>&1
sudo service haproxy start
sudo service haproxy reload
