#!/usr/bin/env bash
# Script that links sites-enabled with sites-available and start nginx
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
rm /run/nginx.pid
