#!/usr/bin/env bash
# Displays numbers from 1 to 100 when the number is multiple of 3 and 5 prints
# fizzbuzz, when is multiple of 3 fizz and when is multiple of 5 buzz
for i in $(seq 1 100);
do
    if [ $((i % 15)) == 0 ]
    then
	echo "FizzBuzz"
    elif [ $((i % 5)) == 0 ]
    then
	echo "Buzz"
    elif [ $((i % 3)) == 0 ]
    then
	echo "Fizz"
    else
	echo "$i"
    fi
done
