#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, using the while
# loop + IFS.
while IFS=":" read USERNAME PASSWORD U_ID G_ID U_ID_INFO H_DIRECTORY COMSHELL;
do
    echo "The user $USERNAME is part of the $G_ID gang, lives in $H_DIRECTORY and rides $COMSHELL. $U_ID's place is protected by the passcode $PASSWORD, more info about the user here: $U_ID_INFO"
done < /etc/passwd
