#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and in the 4th iteration
# prints bad luck in the 8th iteration prints good luck
i="1"
while [ $i -le 10 ]; do
      if [ "$i" == 4 ]
      then
	  echo "bad luck"
      elif [ "$i" == 8 ]
      then
	  echo "good luck"
      else
	  echo "Holberton School"
      fi
      i=$((i+1))
done
