#!/usr/bin/env bash
# This script is displaying numbers from 1 to 20 and in the 4th iteration
# prints bad luck from China in the 8th iteration prints bad luck from Japan and
# in the 17th iteration prints bad luck from Italy
i="1"
while [ $i -le 20 ]; do
      if [ $i == 5 ]
      then
	  echo "bad luck from China"
      elif [ $i == 10 ]
      then
	  echo "bad luck from Japan"
      elif [ $i == 18 ]
      then
	  echo "bad luck from Italy"
      fi
      echo $i
      i=$((i+1))
done
