#!/usr/bin/env bash
# This script is displaying numbers from 1 to 20 and in the 4th iteration
# prints bad luck from China in the 8th iteration prints bad luck from Japan and
# in the 17th iteration prints bad luck from Italy
i="1"
while [ $i -le 20 ]; do
      case $i in
	  5)
	      echo "bad luck from China"
	      ;;
	  10)
	      echo "bad luck from Japan"
	      ;;
	  18)
	      echo "bad luck from Italy"
	      ;;
      esac
      echo $i
      i=$((i+1))
done
